### PR TITLE
Upgrademapboxgltov2 issue111

### PR DESCRIPTION
**Pull request by purpleplum**
Resolves # .

# Why is this change necessary?
Fix issue 111 and 113
# How does it address the issue?
For 111, add dependencies in .yarnrc..yml and run the following:
yarn add mapbox-gl
yarn rebuild
yarn install

For 113, add  willDestroyElement in clickcatcher.js

# What side effects does it have?
mapbox gl js upgraded to v2 and issue 113 errors gone

### CODE REVIEW

**Review by kaden-weber — CHANGES_REQUESTED** [review]
Pull from develop first

**Comment by purpleplum** [comment]
Got it. Will recreate.

**Comment by kaden-weber** [comment]
> Got it. Will recreate.

There's no need to close the PR, you can pull `develop` onto `upgrademapboxgltov2_issue111` and then push the new changes on `upgrademapboxgltov2_issue111`, the PR will be updated automatically.

**Comment by purpleplum** [comment]
Seems the develop branch already has those missing dependencies. No need to change the .yarnrc.yml

**Pull request closed without merging**
