### PR TITLE
initcap municipal before saving and lowercase before filter

### PR DESCRIPTION
**Pull request by purpleplum**
Resolves # 135.

# Why is this change necessary?
Filtering on town/city like Salinas not working since filtering value for municipal was capitalized 
# How does it address the issue?
Make the filtering match case insensitive
# What side effects does it have?
None

### CODE REVIEW

**Comment by purpleplum** [comment]
Needs further check to make sure the change doesn't have a conflict with the check of user municipality with development municipal in development policy.

**Comment by purpleplum** [comment]
Development policy seems to work as expected for verified municipal user.

**Review by kaden-weber — APPROVED** [review]

**Comment by kaden-weber** [comment]
@purpleplum I caught this up to develop, so I wanted you to be able to double check it. Feel free to merge it!

**Comment by purpleplum** [comment]
Looks good. Merged.

**Pull request merged**
